import { useState } from 'react';
import {
  Badge,
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  PageHeader,
  type BadgeVariant,
} from '@/components/ui';
import { cn } from '@/lib/cn';

type HttpMethod = 'GET' | 'POST';

interface EndpointParam {
  name: string;
  type: string;
  required?: boolean;
  description: string;
}

interface EndpointDoc {
  method: HttpMethod;
  path: string;
  description: string;
  params: EndpointParam[];
  exampleRequest: string;
  exampleResponse: string;
}

interface DocCategory {
  id: string;
  name: string;
  description: string;
  endpoints: EndpointDoc[];
}

const METHOD_VARIANT: Record<HttpMethod, BadgeVariant> = {
  GET: 'info',
  POST: 'success',
};

const SWAGGER_RESPONSE =
  'Response schemas are generated by the running service. Use its Swagger URL for the current contract.';

const DOCS: DocCategory[] = [
  {
    id: 'controls',
    name: 'Controls',
    description: 'Implemented controls-service routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/controls',
        description: 'List controls for the authenticated organization.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/controls',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/controls/categories',
        description: 'Return control categories and counts.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/controls/categories',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'evidence',
    name: 'Evidence',
    description: 'Implemented evidence-service routes in the controls API.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/evidence',
        description: 'List evidence for the authenticated organization.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/evidence',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/evidence/stats',
        description: 'Return evidence statistics.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/evidence/stats',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'frameworks',
    name: 'Frameworks',
    description: 'Implemented frameworks-service routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/frameworks',
        description: 'List frameworks for the authenticated organization.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/frameworks',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/frameworks/:id/requirements',
        description: 'List requirements for one framework.',
        params: [
          { name: 'id', type: 'path', required: true, description: 'Framework identifier.' },
          {
            name: 'parentId',
            type: 'query',
            description: 'Optional parent requirement identifier.',
          },
        ],
        exampleRequest: 'curl -k "https://localhost/api/frameworks/FRAMEWORK_ID/requirements"',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'risks',
    name: 'Risks',
    description: 'Implemented controls-service risk routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/risks',
        description: 'List risks using the lightweight response.',
        params: [
          { name: 'page', type: 'query', description: 'Page number.' },
          { name: 'limit', type: 'query', description: 'Page size.' },
        ],
        exampleRequest: 'curl -k "https://localhost/api/risks?page=1&limit=20"',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/risks/dashboard',
        description: 'Return risk dashboard data.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/risks/dashboard',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'audits',
    name: 'Audits',
    description: 'Implemented audit-service routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/audits',
        description: 'List audits for the authenticated organization.',
        params: [
          { name: 'status', type: 'query', description: 'Optional audit status.' },
          { name: 'auditType', type: 'query', description: 'Optional audit type.' },
          { name: 'isExternal', type: 'query', description: 'Optional true/false filter.' },
        ],
        exampleRequest: 'curl -k "https://localhost/api/audits?isExternal=false"',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/audits/dashboard',
        description: 'Return audit dashboard statistics.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/audits/dashboard',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'integrations',
    name: 'Integrations',
    description: 'Catalog and configured integration routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/integrations/types',
        description:
          'Return catalog metadata. Catalog presence does not guarantee a verified connector.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/integrations/types',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'GET',
        path: '/api/integrations',
        description: 'List configured integrations for the authenticated organization.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/integrations',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
  {
    id: 'demo-data',
    name: 'Demo Data',
    description: 'Development-only seed routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/seed/status',
        description: 'Return seed status for the development organization.',
        params: [],
        exampleRequest: 'curl -k https://localhost/api/seed/status',
        exampleResponse: SWAGGER_RESPONSE,
      },
      {
        method: 'POST',
        path: '/api/seed/load-demo',
        description: 'Load demo records. Admin-only and rejected when NODE_ENV is production.',
        params: [],
        exampleRequest: 'curl -k -X POST https://localhost/api/seed/load-demo',
        exampleResponse: SWAGGER_RESPONSE,
      },
    ],
  },
];

function EndpointBlock({ endpoint }: { endpoint: EndpointDoc }) {
  return (
    <div className="rounded-lg border border-surface-200 bg-white">
      <div className="flex items-center gap-3 px-4 py-3 border-b border-surface-200">
        <Badge variant={METHOD_VARIANT[endpoint.method]} capitalize={false}>
          {endpoint.method}
        </Badge>
        <code className="font-mono text-small text-surface-900">{endpoint.path}</code>
      </div>
      <div className="px-4 py-4 space-y-4">
        <p className="text-small text-surface-700">{endpoint.description}</p>

        {endpoint.params.length > 0 && (
          <div>
            <h4 className="text-small font-semibold text-surface-900 mb-2">Parameters</h4>
            <div className="rounded-md border border-surface-200 overflow-hidden">
              <table className="w-full text-small">
                <thead className="bg-surface-50/60">
                  <tr className="text-left text-xs font-medium text-surface-600 uppercase tracking-wider">
                    <th className="px-3 py-2">Name</th>
                    <th className="px-3 py-2">Type</th>
                    <th className="px-3 py-2">Description</th>
                  </tr>
                </thead>
                <tbody>
                  {endpoint.params.map((param) => (
                    <tr key={param.name} className="border-t border-surface-200/60 align-top">
                      <td className="px-3 py-2 font-mono text-surface-900">
                        {param.name}
                        {param.required && <span className="ml-1 text-red-600">*</span>}
                      </td>
                      <td className="px-3 py-2 font-mono text-surface-700">{param.type}</td>
                      <td className="px-3 py-2 text-surface-700">{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <h4 className="text-small font-semibold text-surface-900 mb-2">Local request</h4>
            <pre className="rounded-md border border-surface-200 bg-surface-50/40 p-3 overflow-x-auto text-xs font-mono text-surface-800">
              <code>{endpoint.exampleRequest}</code>
            </pre>
          </div>
          <div>
            <h4 className="text-small font-semibold text-surface-900 mb-2">Response contract</h4>
            <pre className="rounded-md border border-surface-200 bg-surface-50/40 p-3 overflow-x-auto text-xs font-mono text-surface-800 whitespace-pre-wrap">
              <code>{endpoint.exampleResponse}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function DeveloperDocs() {
  const [activeId, setActiveId] = useState<string>(DOCS[0].id);
  const active = DOCS.find((category) => category.id === activeId) ?? DOCS[0];

  return (
    <div className="space-y-5">
      <PageHeader
        title="Developer Docs"
        description="Verified route examples for the current self-hosted services."
      />

      <Card>
        <CardBody>
          <div className="space-y-2 text-small text-surface-700">
            <p>
              The live Swagger documents are the source of truth for request and response schemas:
              local service ports 3001, 3002, 3004, 3005, 3006, and 3007 at <code>/api/docs</code>.
            </p>
            <p>
              The requests below use the local development stack, its self-signed certificate, and
              development authentication. Production requires configured JWT or API-key
              authentication. There is no generic email/password REST login endpoint.
            </p>
          </div>
        </CardBody>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Categories</CardTitle>
            </CardHeader>
            <CardBody density="compact">
              <ul className="space-y-1">
                {DOCS.map((category) => {
                  const isActive = category.id === activeId;
                  return (
                    <li key={category.id}>
                      <button
                        type="button"
                        onClick={() => setActiveId(category.id)}
                        className={cn(
                          'w-full text-left px-3 py-2 rounded-md transition-colors',
                          'focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500',
                          isActive
                            ? 'bg-brand-50 text-brand-800'
                            : 'text-surface-700 hover:bg-surface-100 hover:text-surface-900'
                        )}
                      >
                        <span className="block text-body font-medium">{category.name}</span>
                        <span className="block text-xs text-surface-600 mt-0.5">
                          {category.endpoints.length} endpoint
                          {category.endpoints.length === 1 ? '' : 's'}
                        </span>
                      </button>
                    </li>
                  );
                })}
              </ul>
            </CardBody>
          </Card>
        </div>

        <div className="lg:col-span-2 space-y-4">
          <div>
            <h2 className="text-h2 text-surface-900">{active.name}</h2>
            <p className="text-small text-surface-600 mt-1">{active.description}</p>
          </div>
          <div className="space-y-4">
            {active.endpoints.map((endpoint) => (
              <EndpointBlock key={`${endpoint.method}-${endpoint.path}`} endpoint={endpoint} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
